name: workflow-services

on: 
  push:
    braches:
      - main  

jobs:
  trabajo1:
    runs-on: ubuntu-latest  

    steps:
      - name: "Chekout del repositorio"
        uses: actions/checkout@v2
      - name: listar archivos
        run: ls -la
